# HTCondor Submit File

# Required arguments:
# email           your email
# prefix          analysis prefix 
# sample2reads    3 col tsv: sampleID, read1 fastq, read2 fastq
# outdir          output directory
# threads         number of CPUs
# 
# Usage: 
# condor_submit email=<str> prefix=<str> sample2reads=<path> outdir=<dir> threads=<int> trimmomatic.sub 
#
# Output:
# will output results to $outdir (must be located in /staging)
# 
# Recommendations:
# threads=16


# IMPORTANT! Require execute servers that can access /staging
Requirements = (Target.HasCHTCStaging == true)

# Resource requests
request_cpus = $(threads)
request_memory = 48GB
request_disk = 8GB

# Set notification options (options are Never, Complete, Error or Always)
notify_user   = $(email)
notification  = Error

# Name the batch job
batch_name = "$(prefix)_trimmomatic" 

# Provide the container for our software
universe = container
container_image = docker://staphb/trimmomatic:0.39

# Provide our executable and arguments
executable = trimmomatic.sh
arguments = $(sampleID) $(read1) $(read2) $(outdir) $(threads)

# Track job information (required)
should_transfer_files = IF_NEEDED
transfer_input_files = TruSeq3-PE.fa
when_to_transfer_output = ON_EXIT
transfer_output_files = ""

# Job files (uncomment if desired)
log = $(prefix)_$(sampleID)_trimmomatic.log
output = $(prefix)_$(sampleID)_trimmomatic.out
error = $(prefix)_$(sampleID)_trimmomatic.err

# Tell HTCondor to run our job:
queue sampleID,read1,read2 from $(sample2reads) 
